profile_names = {
    '1' : 'Kleine und mittlere Flughäfen',
    '2' : 'Ressort-Forschungseinrichtungen',
    '3' : 'Nutzung der E-Akte Bund',
    '4' : 'Leitstellen',
    '5' : 'Absicherung von 5G-Campusnetzen Eigenbetrieb',
    '6' : 'Oberste Bundesbehörden',
    '7' : 'Betrieb von UAS Band 1: UAS-Betriebskategorie "Open"(Offen)',
    '8' : 'Basis-Absicherung Kommunalverwaltung',
    '9' : 'Absicherung von 5G-Campusnetzen Fremdbetrieb',
    '10' : 'i-Kfz (Platzhalter)',
    '11' : 'Einnahmeverwaltung des Ministeriums der Finanzen Sachsen-Anhalt (Platzhalter)',
    '12' : 'Bundesgerichte',
    '13' : 'Chemie',
    '14' : 'Hochschulen',
    '15' : 'Weltrauminfrastrukturen',
    '16' : 'Verkehrssteuerungs- und Leitsysteme der Bundesautobahn',
    '17' : 'Papierfabriken',
    '18' : 'Oberste Landesbehörden Deutschlands',
    '19' : 'Handwerksbetriebe (Platzhalter)',
    '20' : 'Reedereien - Landbetrieb',
    '21' : 'Reedereien - Schiffsbetrieb',
    '22' : 'Handwerkskammern',
    '23' : 'Große IT-Dienstleister (Basis)'
}

profiles_mapping = {
    '1' : 'flughafen_profil',
    '2' : 'ressort_forschungseinrichtungen_profil',
    '3' : 'e_akte_profil',
    '4' : 'leitstellen_profil',
    '5' : 'fuenfg_eigenbetrieb_profil',
    '6' : 'oberste_bundesbehoerden_profil',
    '7' : 'uas_profil',
    '8' : 'kommunalverwaltung_profil',
    '9' : 'fuenfg_fremdbetrieb_profil',
    '10' : 'ikfz_profil',
    '11' : 'finanzen_sa_profil',
    '12' : 'bundesgerichte_profil',
    '13' : 'chemie_profil',
    '14' : 'hochschulen_profil',
    '15' : 'weltrauminfrastrukturen_profil',
    '16' : 'bundesautobahn_profil',
    '17' : 'papierfabriken_profil',
    '18' : 'oberste_landesbehoerden_profil',
    '19' : 'handwerksbetriebe_profil',
    '20' : 'reedereien_land_profil',
    '21' : 'reedereien_schiff_profil',
    '22' : 'handwerkskammern_profil',
    '23' : 'grosse_dienstleister_profil'
}

flughafen_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.7': 'Informationssicherheit auf Auslandsreisen',
    'CON.8': 'Software Entwicklung',
    'CON.9': 'Informationsaustausch',
    'CON.10': 'Entwicklung von Webanwendungen',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.1.7': 'Systemmanagement',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.1.2.6': 'NTP Zeitsynchronisation',
    'OPS.2.2': 'Cloud Nutzung',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'OPS.3.2': 'Anbieten von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.1.4': 'Mobile Anwendungen',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.2.3': 'OpenLDAP',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.2': 'Webserver',
    'APP.3.3': 'Fileserver',
    'APP.3.4': 'Samba',
    'APP.3.6': 'DNS Server',
    'APP.4.2': 'SAP ERP System',
    'APP.4.3': 'Relationale Datenbanksysteme',
    'APP.4.4': 'Kubernetes',
    'APP.4.6': 'SAP ABAP Programmierung',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.5.4': 'Unified Communications und Collaboration',
    'APP.6': 'Allgemeine Software',
    'APP.7': 'Entwicklung von Individualsoftware',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.6': 'Containerisierung',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.1.9': 'Terminalserver',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.2.4': 'Clients unter macOS',
    'SYS.2.5': 'Client Virtualisierung',
    'SYS.2.6': 'Virtual Desktop Infrastructure',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.3': 'Eingebettete Systeme',
    'SYS.4.4': 'Allgemeines IoT-Gerät',
    'SYS.4.5': 'Wechseldatenträger',
    'IND.1': 'Prozessleit- und Automatisierungstechnik',
    'IND.2.1': 'Allgemeine ICS Komponente',
    'IND.2.2': 'Speicherprogrammierbare Steuerung',
    'IND.2.3': 'Sensoren und Aktoren',
    'IND.2.4': 'Maschine',
    'IND.2.7': 'Safety Instrumented Systems',
    'IND.3.2': 'Fernwartung im industriellen Umfeld',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.3.4': 'Network Access Control',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'NET.4.3': 'Faxgeräte und Faxserver',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.6': 'Datenträgerarchiv',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume',
    'INF.11': 'Allgemeines Fahrzeug',
    'INF.12': 'Verkabelung',
    'INF.13': 'Technisches Gebäudemanagement',
    'INF.14': 'Gebäudeautomation',
}

ressort_forschungseinrichtungen_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.7': 'Informationssicherheit auf Auslandsreisen',
    'CON.8': 'Software Entwicklung',
    'CON.9': 'Informationsaustausch',
    'CON.11.1': 'Geheimschutz',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.1.2.6': 'NTP Zeitsynchronisation',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.3.2': 'Revisionen auf Basis des Leitfadens IS-Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.1.4': 'Mobile Anwendungen',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.2': 'Webserver',
    'APP.3.3': 'Fileserver',
    'APP.3.6': 'DNS Server',
    'APP.4.2': 'SAP ERP System',
    'APP.4.3': 'Relationale Datenbanksysteme',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.5.4': 'Unified Communications und Collaboration',
    'APP.6': 'Allgemeine Software',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.3': 'Windows Server',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.4.1': 'TK-Anlagen',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume',
    'INF.12': 'Verkabelung',
}

e_akte_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.7': 'Informationssicherheit auf Auslandsreisen',
    'CON.9': 'Informationsaustausch',
    'CON.11.1': 'Geheimschutz',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.1.7': 'Systemmanagement',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.1.2.6': 'NTP Zeitsynchronisation',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.3.2': 'Revisionen auf Basis des Leitfadens IS-Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.3.3': 'Fileserver',
    'APP.3.6': 'DNS Server',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.5.4': 'Unified Communications und Collaboration',
    'APP.6': 'Allgemeine Software',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.5': 'Wechseldatenträger',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume',
    'INF.12': 'Verkabelung',
}

leitstellen_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.9': 'Informationsaustausch',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.1.7': 'Systemmanagement',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.1.2.6': 'NTP Zeitsynchronisation',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.2': 'Webserver',
    'APP.3.3': 'Fileserver',
    'APP.3.6': 'DNS Server',
    'APP.4.3': 'Relationale Datenbanksysteme',
    'APP.4.4': 'Kubernetes',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.6': 'Allgemeine Software',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.6': 'Containerisierung',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.2.5': 'Client Virtualisierung',
    'SYS.3.1': 'Laptops',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.5': 'Wechseldatenträger',
    'IND.1': 'Prozessleit- und Automatisierungstechnik',
    'IND.2.1': 'Allgemeine ICS Komponente',
    'IND.2.2': 'Speicherprogrammierbare Steuerung',
    'IND.2.3': 'Sensoren und Aktoren',
    'IND.2.4': 'Maschine',
    'IND.2.7': 'Safety Instrumented Systems',
    'IND.3.2': 'Fernwartung im industriellen Umfeld',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'NET.4.3': 'Faxgeräte und Faxserver',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.6': 'Datenträgerarchiv',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume',
    'INF.12': 'Verkabelung',
    'INF.13': 'Technisches Gebäudemanagement',
    'INF.14': 'Gebäudeautomation',
}

fuenfg_eigenbetrieb_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.9': 'Informationsaustausch',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.1.7': 'Systemmanagement',
    'OPS.1.2.5': 'Fernwartung',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.2': 'Webbrowser',
    'APP.6': 'Allgemeine Software',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.6': 'Containerisierung',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.2.4': 'Clients unter macOS',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.3': 'Eingebettete Systeme',
    'SYS.4.4': 'Allgemeines IoT-Gerät',
    'IND.1': 'Prozessleit- und Automatisierungstechnik',
    'IND.2.1': 'Allgemeine ICS Komponente',
    'IND.2.2': 'Speicherprogrammierbare Steuerung',
    'IND.2.3': 'Sensoren und Aktoren',
    'IND.2.4': 'Maschine',
    'IND.2.7': 'Safety Instrumented Systems',
    'IND.3.2': 'Fernwartung im industriellen Umfeld',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.12': 'Verkabelung',
}

oberste_bundesbehoerden_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.7': 'Informationssicherheit auf Auslandsreisen',
    'CON.9': 'Informationsaustausch',
    'CON.11.1': 'Geheimschutz',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.1.2.6': 'NTP Zeitsynchronisation',
    'OPS.2.2': 'Cloud Nutzung',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.2': 'Revisionen auf Basis des Leitfadens IS-Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.1.4': 'Mobile Anwendungen',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.2.3': 'OpenLDAP',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.2': 'Webserver',
    'APP.3.3': 'Fileserver',
    'APP.3.6': 'DNS Server',
    'APP.4.3': 'Relationale Datenbanksysteme',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.5.4': 'Unified Communications und Collaboration',
    'APP.6': 'Allgemeine Software',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.4': 'Allgemeines IoT-Gerät',
    'SYS.4.5': 'Wechseldatenträger',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.3.4': 'Network Access Control',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.6': 'Datenträgerarchiv',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume',
    'INF.11': 'Allgemeines Fahrzeug',
    'INF.12': 'Verkabelung',
    'INF.13': 'Technisches Gebäudemanagement',
    'INF.14': 'Gebäudeautomation'
}

uas_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.9': 'Informationsaustausch',
    'CON.11.1': 'Geheimschutz',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.1.7': 'Systemmanagement',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.1.2.6': 'NTP Zeitsynchronisation',
    'OPS.2.2': 'Cloud Nutzung',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'OPS.3.2': 'Anbieten von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.2': 'Webbrowser',
    'APP.1.4': 'Mobile Anwendungen',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.2.3': 'OpenLDAP',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.2': 'Webserver',
    'APP.3.3': 'Fileserver',
    'APP.3.4': 'Samba',
    'APP.4.4': 'Kubernetes',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'APP.5.4': 'Unified Communications und Collaboration',
    'APP.6': 'Allgemeine Software',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.6': 'Containerisierung',
    'SYS.1.7': 'IBM Z',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.1.9': 'Terminalserver',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.2.4': 'Clients unter macOS',
    'SYS.2.5': 'Client Virtualisierung',
    'SYS.2.6': 'Virtual Desktop Infrastructure',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.3': 'Eingebettete Systeme',
    'SYS.4.4': 'Allgemeines IoT-Gerät',
    'SYS.4.5': 'Wechseldatenträger',
    'IND.1': 'Prozessleit- und Automatisierungstechnik',
    'IND.2.1': 'Allgemeine ICS Komponente',
    'IND.2.2': 'Speicherprogrammierbare Steuerung',
    'IND.2.3': 'Sensoren und Aktoren',
    'IND.2.4': 'Maschine',
    'IND.2.7': 'Safety Instrumented Systems',
    'IND.3.2': 'Fernwartung im industriellen Umfeld',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.3.4': 'Network Access Control',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'NET.4.3': 'Faxgeräte und Faxserver',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.6': 'Datenträgerarchiv',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume',
    'INF.11': 'Allgemeines Fahrzeug',
    'INF.12': 'Verkabelung',
    'INF.13': 'Technisches Gebäudemanagement',
    'INF.14': 'Gebäudeautomation'
}

kommunalverwaltung_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.9': 'Informationsaustausch',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.2.2': 'Cloud Nutzung',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.9': 'Terminalserver',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.5': 'Client Virtualisierung',
    'SYS.2.6': 'Virtual Desktop Infrastructure',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.5': 'Wechseldatenträger',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.2': 'Webserver',
    'APP.3.3': 'Fileserver',
    'APP.3.6': 'DNS Server',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.6': 'Allgemeine Software',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'NET.4.3': 'Faxgeräte und Faxserver',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.6': 'Datenträgerarchiv',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume',
    'INF.11': 'Allgemeines Fahrzeug',
    'INF.12': 'Verkabelung'
}

fuenfg_fremdbetrieb_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.9': 'Informationsaustausch',
    'CON.10': 'Entwicklung von Webanwendungen',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.2': 'Webbrowser',
    'APP.6': 'Allgemeine Software',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.2.4': 'Clients unter macOS',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.3': 'Eingebettete Systeme',
    'SYS.4.4': 'Allgemeines IoT-Gerät',
    'IND.1': 'Prozessleit- und Automatisierungstechnik',
    'IND.2.1': 'Allgemeine ICS Komponente',
    'IND.2.2': 'Speicherprogrammierbare Steuerung',
    'IND.2.3': 'Sensoren und Aktoren',
    'IND.2.4': 'Maschine',
    'IND.2.7': 'Safety Instrumented Systems',
    'IND.3.2': 'Fernwartung im industriellen Umfeld',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.12': 'Verkabelung',
    'INF.13': 'Technisches Gebäudemanagement',
    'INF.14': 'Gebäudeautomation'
}

# Platzhalter, da Profil geheim. Bei Nutzung nicht benötigte Bausteine manuell entfernen
ikfz_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.7': 'Informationssicherheit auf Auslandsreisen',
    'CON.8': 'Software Entwicklung',
    'CON.9': 'Informationsaustausch',
    'CON.10': 'Entwicklung von Webanwendungen',
    'CON.11.1': 'Geheimschutz',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.1.7': 'Systemmanagement',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.1.2.6': 'NTP Zeitsynchronisation',
    'OPS.2.2': 'Cloud Nutzung',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'OPS.3.2': 'Anbieten von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.3.2': 'Revisionen auf Basis des Leitfadens IS-Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.1.4': 'Mobile Anwendungen',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.2.3': 'OpenLDAP',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.2': 'Webserver',
    'APP.3.3': 'Fileserver',
    'APP.3.4': 'Samba',
    'APP.3.6': 'DNS Server',
    'APP.4.2': 'SAP ERP System',
    'APP.4.3': 'Relationale Datenbanksysteme',
    'APP.4.4': 'Kubernetes',
    'APP.4.6': 'SAP ABAP Programmierung',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.5.4': 'Unified Communications und Collaboration',
    'APP.6': 'Allgemeine Software',
    'APP.7': 'Entwicklung von Individualsoftware',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.6': 'Containerisierung',
    'SYS.1.7': 'IBM Z',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.1.9': 'Terminalserver',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.2.4': 'Clients unter macOS',
    'SYS.2.5': 'Client Virtualisierung',
    'SYS.2.6': 'Virtual Desktop Infrastructure',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.3': 'Eingebettete Systeme',
    'SYS.4.4': 'Allgemeines IoT-Gerät',
    'SYS.4.5': 'Wechseldatenträger',
    'IND.1': 'Prozessleit- und Automatisierungstechnik',
    'IND.2.1': 'Allgemeine ICS Komponente',
    'IND.2.2': 'Speicherprogrammierbare Steuerung',
    'IND.2.3': 'Sensoren und Aktoren',
    'IND.2.4': 'Maschine',
    'IND.2.7': 'Safety Instrumented Systems',
    'IND.3.2': 'Fernwartung im industriellen Umfeld',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.3.4': 'Network Access Control',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'NET.4.3': 'Faxgeräte und Faxserver',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.6': 'Datenträgerarchiv',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume',
    'INF.11': 'Allgemeines Fahrzeug',
    'INF.12': 'Verkabelung',
    'INF.13': 'Technisches Gebäudemanagement',
    'INF.14': 'Gebäudeautomation'
}

# Platzhalter, es muss erst eine Modellierung stattfinden, um nicht relevante Bausteine ausschließen zu können
finanzen_sa_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.7': 'Informationssicherheit auf Auslandsreisen',
    'CON.8': 'Software Entwicklung',
    'CON.9': 'Informationsaustausch',
    'CON.10': 'Entwicklung von Webanwendungen',
    'CON.11.1': 'Geheimschutz',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.1.7': 'Systemmanagement',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.1.2.6': 'NTP Zeitsynchronisation',
    'OPS.2.2': 'Cloud Nutzung',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'OPS.3.2': 'Anbieten von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.3.2': 'Revisionen auf Basis des Leitfadens IS-Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.1.4': 'Mobile Anwendungen',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.2.3': 'OpenLDAP',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.2': 'Webserver',
    'APP.3.3': 'Fileserver',
    'APP.3.4': 'Samba',
    'APP.3.6': 'DNS Server',
    'APP.4.2': 'SAP ERP System',
    'APP.4.3': 'Relationale Datenbanksysteme',
    'APP.4.4': 'Kubernetes',
    'APP.4.6': 'SAP ABAP Programmierung',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.5.4': 'Unified Communications und Collaboration',
    'APP.6': 'Allgemeine Software',
    'APP.7': 'Entwicklung von Individualsoftware',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.6': 'Containerisierung',
    'SYS.1.7': 'IBM Z',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.1.9': 'Terminalserver',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.2.4': 'Clients unter macOS',
    'SYS.2.5': 'Client Virtualisierung',
    'SYS.2.6': 'Virtual Desktop Infrastructure',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.3': 'Eingebettete Systeme',
    'SYS.4.4': 'Allgemeines IoT-Gerät',
    'SYS.4.5': 'Wechseldatenträger',
    'IND.1': 'Prozessleit- und Automatisierungstechnik',
    'IND.2.1': 'Allgemeine ICS Komponente',
    'IND.2.2': 'Speicherprogrammierbare Steuerung',
    'IND.2.3': 'Sensoren und Aktoren',
    'IND.2.4': 'Maschine',
    'IND.2.7': 'Safety Instrumented Systems',
    'IND.3.2': 'Fernwartung im industriellen Umfeld',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.3.4': 'Network Access Control',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'NET.4.3': 'Faxgeräte und Faxserver',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.6': 'Datenträgerarchiv',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume',
    'INF.11': 'Allgemeines Fahrzeug',
    'INF.12': 'Verkabelung',
    'INF.13': 'Technisches Gebäudemanagement',
    'INF.14': 'Gebäudeautomation'
}

bundesgerichte_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.7': 'Informationssicherheit auf Auslandsreisen',
    'CON.9': 'Informationsaustausch',
    'CON.11.1': 'Geheimschutz',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.1.2.6': 'NTP Zeitsynchronisation',
    'OPS.2.2': 'Cloud Nutzung',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.1.4': 'Mobile Anwendungen',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.2.3': 'OpenLDAP',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.2': 'Webserver',
    'APP.3.3': 'Fileserver',
    'APP.3.6': 'DNS Server',
    'APP.4.3': 'Relationale Datenbanksysteme',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.5.4': 'Unified Communications und Collaboration',
    'APP.6': 'Allgemeine Software',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.5': 'Wechseldatenträger',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.3.4': 'Network Access Control',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume',
    'INF.12': 'Verkabelung',
}

chemie_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.8': 'Software Entwicklung',
    'CON.9': 'Informationsaustausch',
    'CON.10': 'Entwicklung von Webanwendungen',
    'CON.11.1': 'Geheimschutz',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.1.7': 'Systemmanagement',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.1.2.6': 'NTP Zeitsynchronisation',
    'OPS.2.2': 'Cloud Nutzung',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'OPS.3.2': 'Anbieten von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.1.4': 'Mobile Anwendungen',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.2.3': 'OpenLDAP',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.2': 'Webserver',
    'APP.3.3': 'Fileserver',
    'APP.3.4': 'Samba',
    'APP.3.6': 'DNS Server',
    'APP.4.2': 'SAP ERP System',
    'APP.4.3': 'Relationale Datenbanksysteme',
    'APP.4.4': 'Kubernetes',
    'APP.5.4': 'Unified Communications und Collaboration',
    'APP.6': 'Allgemeine Software',
    'APP.7': 'Entwicklung von Individualsoftware',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.6': 'Containerisierung',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.1.9': 'Terminalserver',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.2.4': 'Clients unter macOS',
    'SYS.2.5': 'Client Virtualisierung',
    'SYS.2.6': 'Virtual Desktop Infrastructure',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.3': 'Eingebettete Systeme',
    'SYS.4.4': 'Allgemeines IoT-Gerät',
    'SYS.4.5': 'Wechseldatenträger',
    'IND.1': 'Prozessleit- und Automatisierungstechnik',
    'IND.2.1': 'Allgemeine ICS Komponente',
    'IND.2.2': 'Speicherprogrammierbare Steuerung',
    'IND.2.3': 'Sensoren und Aktoren',
    'IND.2.4': 'Maschine',
    'IND.2.7': 'Safety Instrumented Systems',
    'IND.3.2': 'Fernwartung im industriellen Umfeld',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.3.4': 'Network Access Control',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume',
    'INF.12': 'Verkabelung',
    'INF.13': 'Technisches Gebäudemanagement',
    'INF.14': 'Gebäudeautomation'
}

hochschulen_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.7': 'Informationssicherheit auf Auslandsreisen',
    'CON.8': 'Software Entwicklung',
    'CON.9': 'Informationsaustausch',
    'CON.10': 'Entwicklung von Webanwendungen',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.1.7': 'Systemmanagement',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.1.2.6': 'NTP Zeitsynchronisation',
    'OPS.2.2': 'Cloud Nutzung',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'OPS.3.2': 'Anbieten von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.1.4': 'Mobile Anwendungen',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.2.3': 'OpenLDAP',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.2': 'Webserver',
    'APP.3.3': 'Fileserver',
    'APP.3.4': 'Samba',
    'APP.3.6': 'DNS Server',
    'APP.4.2': 'SAP ERP System',
    'APP.4.3': 'Relationale Datenbanksysteme',
    'APP.4.4': 'Kubernetes',
    'APP.4.6': 'SAP ABAP Programmierung',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.6': 'Allgemeine Software',
    'APP.7': 'Entwicklung von Individualsoftware',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.6': 'Containerisierung',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.2.4': 'Clients unter macOS',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.4': 'Allgemeines IoT-Gerät',
    'SYS.4.5': 'Wechseldatenträger',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.6': 'Datenträgerarchiv',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume',
    'INF.12': 'Verkabelung',
    'INF.13': 'Technisches Gebäudemanagement',
    'INF.14': 'Gebäudeautomation'
}

weltrauminfrastrukturen_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.7': 'Informationssicherheit auf Auslandsreisen',
    'CON.8': 'Software Entwicklung',
    'CON.9': 'Informationsaustausch',
    'CON.11.1': 'Geheimschutz',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.1.7': 'Systemmanagement',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.1.2.6': 'NTP Zeitsynchronisation',
    'OPS.2.2': 'Cloud Nutzung',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'OPS.3.2': 'Anbieten von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.3.2': 'Revisionen auf Basis des Leitfadens IS-Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.1.4': 'Mobile Anwendungen',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.2.3': 'OpenLDAP',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.2': 'Webserver',
    'APP.3.3': 'Fileserver',
    'APP.3.6': 'DNS Server',
    'APP.4.2': 'SAP ERP System',
    'APP.4.3': 'Relationale Datenbanksysteme',
    'APP.4.4': 'Kubernetes',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.5.4': 'Unified Communications und Collaboration',
    'APP.6': 'Allgemeine Software',
    'APP.7': 'Entwicklung von Individualsoftware',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.6': 'Containerisierung',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.1.9': 'Terminalserver',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.2.4': 'Clients unter macOS',
    'SYS.2.5': 'Client Virtualisierung',
    'SYS.2.6': 'Virtual Desktop Infrastructure',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.3': 'Eingebettete Systeme',
    'IND.1': 'Prozessleit- und Automatisierungstechnik',
    'IND.2.1': 'Allgemeine ICS Komponente',
    'IND.2.2': 'Speicherprogrammierbare Steuerung',
    'IND.2.3': 'Sensoren und Aktoren',
    'IND.2.4': 'Maschine',
    'IND.2.7': 'Safety Instrumented Systems',
    'IND.3.2': 'Fernwartung im industriellen Umfeld',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.3.4': 'Network Access Control',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.11': 'Allgemeines Fahrzeug',
    'INF.12': 'Verkabelung'
}

bundesautobahn_profil = {
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'CON.1': 'Kryptokonzept',
    'CON.3': 'Datensicherungskonzept',
    'CON.8': 'Software Entwicklung',
    'CON.10': 'Entwicklung von Webanwendungen',
    'CON.11.1': 'Geheimschutz',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.1.7': 'Systemmanagement',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.1.2.6': 'NTP Zeitsynchronisation',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'OPS.3.2': 'Anbieten von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.2.3': 'OpenLDAP',
    'APP.3.6': 'DNS Server',
    'APP.4.3': 'Relationale Datenbanksysteme',
    'APP.4.4': 'Kubernetes',
    'APP.6': 'Allgemeine Software',
    'APP.7': 'Entwicklung von Individualsoftware',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.6': 'Containerisierung',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.1.9': 'Terminalserver',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.2.5': 'Client Virtualisierung',
    'SYS.2.6': 'Virtual Desktop Infrastructure',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.3': 'Eingebettete Systeme',
    'IND.1': 'Prozessleit- und Automatisierungstechnik',
    'IND.2.1': 'Allgemeine ICS Komponente',
    'IND.2.2': 'Speicherprogrammierbare Steuerung',
    'IND.2.3': 'Sensoren und Aktoren',
    'IND.2.4': 'Maschine',
    'IND.3.2': 'Fernwartung im industriellen Umfeld',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.4': 'Network Access Control',
    'NET.4.2': 'VoIP',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.7': 'Büroarbeitsplatz',
    'INF.12': 'Verkabelung',
    'INF.13': 'Technisches Gebäudemanagement',
    'INF.14': 'Gebäudeautomation'
}

papierfabriken_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.7': 'Informationssicherheit auf Auslandsreisen',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.2.2': 'Cloud Nutzung',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'OPS.3.2': 'Anbieten von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.3.1': 'Audits und Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.1.4': 'Mobile Anwendungen',
    'APP.4.2': 'SAP ERP System',
    'APP.4.3': 'Relationale Datenbanksysteme',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.4': 'Allgemeines IoT-Gerät',
    'SYS.4.5': 'Wechseldatenträger',
    'IND.1': 'Prozessleit- und Automatisierungstechnik',
    'IND.2.1': 'Allgemeine ICS Komponente',
    'IND.2.2': 'Speicherprogrammierbare Steuerung',
    'IND.2.3': 'Sensoren und Aktoren',
    'IND.2.4': 'Maschine',
    'IND.2.7': 'Safety Instrumented Systems',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'NET.4.3': 'Faxgeräte und Faxserver',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.7': 'Büroarbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume'
}

oberste_landesbehoerden_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.9': 'Informationsaustausch',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.3.2': 'Revisionen auf Basis des Leitfadens IS-Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.1.4': 'Mobile Anwendungen',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.3.3': 'Fileserver',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.6': 'Allgemeine Software',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'NET.4.3': 'Faxgeräte und Faxserver',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume'
}

# Platzhalter, da nur für Mitglieder
handwerksbetriebe_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.7': 'Informationssicherheit auf Auslandsreisen',
    'CON.8': 'Software Entwicklung',
    'CON.9': 'Informationsaustausch',
    'CON.10': 'Entwicklung von Webanwendungen',
    'CON.11.1': 'Geheimschutz',
    'OPS.1.1.1': 'Allgemeiner IT Betrieb',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.1.7': 'Systemmanagement',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.1.2.6': 'NTP Zeitsynchronisation',
    'OPS.2.2': 'Cloud Nutzung',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'OPS.3.2': 'Anbieten von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.3.2': 'Revisionen auf Basis des Leitfadens IS-Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.1.4': 'Mobile Anwendungen',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.2.3': 'OpenLDAP',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.2': 'Webserver',
    'APP.3.3': 'Fileserver',
    'APP.3.4': 'Samba',
    'APP.3.6': 'DNS Server',
    'APP.4.2': 'SAP ERP System',
    'APP.4.3': 'Relationale Datenbanksysteme',
    'APP.4.4': 'Kubernetes',
    'APP.4.6': 'SAP ABAP Programmierung',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.5.4': 'Unified Communications und Collaboration',
    'APP.6': 'Allgemeine Software',
    'APP.7': 'Entwicklung von Individualsoftware',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.6': 'Containerisierung',
    'SYS.1.7': 'IBM Z',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.1.9': 'Terminalserver',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.2.4': 'Clients unter macOS',
    'SYS.2.5': 'Client Virtualisierung',
    'SYS.2.6': 'Virtual Desktop Infrastructure',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.3': 'Eingebettete Systeme',
    'SYS.4.4': 'Allgemeines IoT-Gerät',
    'SYS.4.5': 'Wechseldatenträger',
    'IND.1': 'Prozessleit- und Automatisierungstechnik',
    'IND.2.1': 'Allgemeine ICS Komponente',
    'IND.2.2': 'Speicherprogrammierbare Steuerung',
    'IND.2.3': 'Sensoren und Aktoren',
    'IND.2.4': 'Maschine',
    'IND.2.7': 'Safety Instrumented Systems',
    'IND.3.2': 'Fernwartung im industriellen Umfeld',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.3.4': 'Network Access Control',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'NET.4.3': 'Faxgeräte und Faxserver',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.6': 'Datenträgerarchiv',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume',
    'INF.11': 'Allgemeines Fahrzeug',
    'INF.12': 'Verkabelung',
    'INF.13': 'Technisches Gebäudemanagement',
    'INF.14': 'Gebäudeautomation'
}

reedereien_land_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.7': 'Informationssicherheit auf Auslandsreisen',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.2.2': 'Cloud Nutzung',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'OPS.3.2': 'Anbieten von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.3.1': 'Audits und Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.1.4': 'Mobile Anwendungen',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.3': 'Fileserver',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.6': 'Allgemeine Software',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.4': 'Allgemeines IoT-Gerät',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'NET.4.3': 'Faxgeräte und Faxserver',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.12': 'Verkabelung'
}

reedereien_schiff_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.7': 'Informationssicherheit auf Auslandsreisen',
    'CON.8': 'Software Entwicklung',
    'CON.9': 'Informationsaustausch',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.1.2.5': 'Fernwartung',
    'OPS.1.2.6': 'NTP Zeitsynchronisation',
    'OPS.2.2': 'Cloud Nutzung',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'OPS.3.2': 'Anbieten von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.3.2': 'Revisionen auf Basis des Leitfadens IS-Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.1.4': 'Mobile Anwendungen',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.2.3': 'OpenLDAP',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.2': 'Webserver',
    'APP.3.3': 'Fileserver',
    'APP.3.4': 'Samba',
    'APP.3.6': 'DNS Server',
    'APP.4.3': 'Relationale Datenbanksysteme',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.6': 'Allgemeine Software',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.6': 'Containerisierung',
    'SYS.1.7': 'IBM Z',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.1.9': 'Terminalserver',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.2.4': 'Clients unter macOS',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.4': 'Allgemeines IoT-Gerät',
    'SYS.4.5': 'Wechseldatenträger',
    'IND.1': 'Prozessleit- und Automatisierungstechnik',
    'IND.2.1': 'Allgemeine ICS Komponente',
    'IND.2.2': 'Speicherprogrammierbare Steuerung',
    'IND.2.3': 'Sensoren und Aktoren',
    'IND.2.4': 'Maschine',
    'IND.2.7': 'Safety Instrumented Systems',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'NET.4.3': 'Faxgeräte und Faxserver',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.5': 'Raum sowie Schrank für technische Infrastruktur',
    'INF.6': 'Datenträgerarchiv',
    'INF.7': 'Büroarbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume',
    'INF.12': 'Verkabelung'
}

handwerkskammern_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'CON.7': 'Informationssicherheit auf Auslandsreisen',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.1.1.5': 'Protokollierung',
    'OPS.1.1.6': 'Software, Tests und Freigaben',
    'OPS.1.2.2': 'Archivierung',
    'OPS.1.2.4': 'Telearbeit',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'OPS.3.2': 'Anbieten von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.2.2': 'Vorsorge für die IT-Forensik',
    'DER.2.3': 'Bereinigung weitreichender Sicherheitsvorfälle',
    'DER.3.1': 'Audits und Revisionen',
    'DER.4': 'Notfallmanagement',
    'APP.1.1': 'Office Produkte',
    'APP.1.2': 'Webbrowser',
    'APP.2.1': 'Allgemeiner Verzeichnisdienst',
    'APP.2.2': 'Active Directory Domain Services',
    'APP.3.1': 'Webanwendungen und Webservices',
    'APP.3.2': 'Webserver',
    'APP.3.3': 'Fileserver',
    'APP.3.4': 'Samba',
    'APP.3.6': 'DNS Server',
    'APP.4.3': 'Relationale Datenbanksysteme',
    'APP.5.2': 'Microsoft Exchange und Outlook',
    'APP.5.3': 'Allgemeiner Email Client und Server',
    'APP.6': 'Allgemeine Software',
    'SYS.1.1': 'Allgemeiner Server',
    'SYS.1.2.2': 'Windows Server 2012',
    'SYS.1.2.3': 'Windows Server',
    'SYS.1.3': 'Server unter Linux und Unix',
    'SYS.1.5': 'Virtualisierung',
    'SYS.1.8': 'Speicherlösungen',
    'SYS.2.1': 'Allgemeiner Client',
    'SYS.2.2.3': 'Clients unter Windows',
    'SYS.2.3': 'Clients unter Linux und Unix',
    'SYS.3.1': 'Laptops',
    'SYS.3.2.1': 'Allgemeine Smartphones und Tablets',
    'SYS.3.2.2': 'Mobile Device Management',
    'SYS.3.2.3': 'iOS for Enterprise',
    'SYS.3.2.4': 'Android',
    'SYS.3.3': 'Mobiltelefon',
    'SYS.4.1': 'Drucker, Kopierer und Multifunktionsgeräte',
    'SYS.4.4': 'Allgemeines IoT-Gerät',
    'SYS.4.5': 'Wechseldatenträger',
    'IND.1': 'Prozessleit- und Automatisierungstechnik',
    'IND.2.1': 'Allgemeine ICS Komponente',
    'IND.2.2': 'Speicherprogrammierbare Steuerung',
    'IND.2.3': 'Sensoren und Aktoren',
    'IND.2.4': 'Maschine',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.2.1': 'WLAN Betrieb',
    'NET.2.2': 'WLAN Nutzung',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.7': 'Büroarbeitsplatz',
    'INF.8': 'Häuslicher Arbeitsplatz',
    'INF.9': 'Mobiler Arbeitsplatz',
    'INF.10': 'Besprechungs-, Veranstaltungs- und Schulungsräume',
    'INF.12': 'Verkabelung',
}

grosse_dienstleister_profil = {
    'ISMS.1': 'Sicherheitsmanagement',
    'ORP.1': 'Organisation',
    'ORP.2': 'Personal',
    'ORP.3': 'Sensibilisierung und Schulung zur Informationssicherheit',
    'ORP.4': 'Identitäts- und Berechtigungsmanagement',
    'ORP.5': 'Compliance Management',
    'CON.1': 'Kryptokonzept',
    'CON.2': 'Datenschutz',
    'CON.3': 'Datensicherungskonzept',
    'CON.6': 'Löschen und Vernichten',
    'OPS.1.1.2': 'Ordnungsgemäße IT Administration',
    'OPS.1.1.3': 'Patch und Änderungsmanagement',
    'OPS.1.1.4': 'Schutz vor Schadprogrammen',
    'OPS.2.3': 'Nutzung von Outsourcing',
    'OPS.3.2': 'Anbieten von Outsourcing',
    'DER.1': 'Detektion von sicherheitsrelevanten Ereignissen',
    'DER.2.1': 'Behandlung von Sicherheitsvorfällen',
    'DER.4': 'Notfallmanagement',
    'NET.1.1': 'Netzarchitektur und -design',
    'NET.1.2': 'Netzmanagement',
    'NET.3.1': 'Router und Switches',
    'NET.3.2': 'Firewall',
    'NET.3.3': 'VPN',
    'NET.3.4': 'Network Access Control',
    'NET.4.1': 'TK-Anlagen',
    'NET.4.2': 'VoIP',
    'NET.4.3': 'Faxgeräte und Faxserver',
    'INF.1': 'Allgemeines Gebäude',
    'INF.2': 'Rechenzentrum und Serverraum',
    'INF.7': 'Büroarbeitsplatz',
    'INF.12': 'Verkabelung'
}